image: Visual Studio 2017 Preview
environment:
  VCPKG_DEFAULT_TRIPLET: x64-windows
cache:
  - C:\tools\vcpkg\installed
configuration: Release
before_build:
  - ps: Update-AppveyorBuild -Version (git describe --tags)
  - ps: |
      pushd C:\tools\vcpkg
      git pull
      .\bootstrap-vcpkg.bat
      vcpkg integrate install
      vcpkg install libarchive boost-program-options boost-format
      vcpkg upgrade --no-dry-run
      popd
after_build:
  - ps: |
      $project = $Env:APPVEYOR_PROJECT_NAME
      $name = "$project-$(git describe --tags).zip"
      $dir = "x64\$Env:CONFIGURATION"
      7z a $name "$dir\$project.exe" "$dir\*.dll" "$project\LICENSE" "$project\LICENSE-3RD-PARTY"
      if ($Env:APPVEYOR_REPO_TAG -eq 'true') {
          $hash = (Get-FileHash $name -Algorithm SHA256).Hash
          $version = (git describe --tags).Substring(1)
          cd choco
          (cat "$project.nuspec") -replace '{VERSION}', $version | sc "$project.nuspec" -Encoding Ascii
          (cat tools\chocolateyInstall.ps1) -replace '{VERSION}', $version | sc tools\chocolateyInstall.ps1 -Encoding Ascii
          (cat tools\chocolateyInstall.ps1) -replace '{CHECKSUM}', $hash | sc tools\chocolateyInstall.ps1 -Encoding Ascii
          choco pack
      }
artifacts:
  - path: '*.zip'
  - path: choco\*.nupkg
deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    description: |
      **Release Notes**
      - See https://github.com/DDoSolitary/LxRunOffline/issues/36.
    auth_token:
      secure: 26bYTa3iIxBxle/n6T9sou88hpnz7mK5HoXqSPECwyu7LVI0F28Fl3/Z+T1Y/2Kj
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    artifact: /.*\.nupkg/
    server: https://push.chocolatey.org/
    api_key:
      secure: O5vJKMFYeafCP5lAd3ABYUhYE0qhnL7b0dDphDYHiabv2DovKSyb67fm5PX6aUMg
    on:
      appveyor_repo_tag: true
